### ISSUE TITLE
 Return correct content type

### ISSUE THREAD

**Issue by johnjohndoe** [criticalmaps/criticalmaps-web#1]
The JSON response from the API does not return the correct content type:

```
$ curl -s -D - http://api.criticalmaps.net/twitter/get.php

HTTP/1.1 200 OK
Date: Sun, 04 Oct 2015 22:27:23 GMT
Server: Apache
X-Powered-By: PHP/5.4.44
Transfer-Encoding: chunked
Content-Type: text/html
```

It should be `Content-Type: application/json;charset=utf-8` instead.

**Comment by stephanlindauer** [comment]
hey tobias, can't find your email address. can you join https://criticalmaps.slack.com/ ?

**Comment by johnjohndoe** [comment]
Same problem with `http://api.criticalmaps.net/postv2`.

**Comment by stephanlindauer** [comment]
moved to https://github.com/criticalmaps/criticalmaps-api/issues/1
