### ISSUE TITLE
Load map tiles via HTTPS

### ISSUE THREAD

**Issue by bastei** [criticalmaps/criticalmaps-web#18]
Now as the site is running via HTTPS (:thumbsup:) the tiles on the map result in mixed-content warnings as [they are loaded via HTTP](https://github.com/criticalmaps/criticalmaps-web/blob/master/src/map.php#L25). They could be replaced by this tile URL for example:
`https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`

**Comment by stephanlindauer** [comment]
fixed. thanks for reporting!
