### ISSUE TITLE
Add bike counter to map

### ISSUE THREAD

**Issue by JonathanSchubert** [criticalmaps/criticalmaps-web#20]
Hey, cheers for the nice project!

Would be great to see a counter of visible bikes on the web-map and the app-map.
Could be similar to:
https://github.com/JonathanSchubert/criticalmaps-web-counter

**Comment by stephanlindauer** [comment]
hi jonathan, thanks for the suggestion.
i kinda feel like this is something that sould be done in the backend. when the clients ask for locations it could (not a requirement) include it's own bounding box and get results based on that. getting the amount of locations in the View Port would then just be a matter of calling `.length` plus we this would optimize performance on the clients (for the cost of having more load on the server, but :man_shrugging: :wink: )
sounds like a plan?

ref:
https://stackoverflow.com/questions/20757480/get-boundingbox-of-only-visible-area-of-map-in-osmdroid
https://leafletjs.com/reference-1.3.0.html#bounds
