### ISSUE TITLE
Tiles not loading at higher zoom levels

### ISSUE THREAD

**Issue by genevievecory** [criticalmaps/criticalmaps-web#49]
Reported via Facebook and reproduced.

https://www.criticalmaps.net/map#10/52.4372/13.8084 -- some tiles don't load at higher zoom levels.  Server error 429 too many requests?
![2020-03-16 09_10_46-Critical Maps – Critical Mass app for Android and iOS](https://user-images.githubusercontent.com/50321664/76736358-f00e1000-6766-11ea-87df-e29a9332c9de.png)

**Comment by stephanlindauer** [comment]
> The Wikimedia Maps service was recently hit with a large amount of traffic coming from non-Wikimedia websites that caused a service disruption. The Wikimedia Foundation system administrators decided to block all traffic to Wikimedia Maps from non-Wikimedia websites in order to ensure that it remained available for Wikimedia projects. The WMF has not yet decided how long this restriction will last or if it will become permanent. T244278 should have more information as it becomes available.

https://phabricator.wikimedia.org/T245145#5880898

maybe should switch to another tiles server until they have resolved their problems. :/
